# This is a basic workflow to help you get started with Actions

name: code-deployment
on: push
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run lint
        run: |
          cd 04_project/04_Practice_Project
          npm install
          npm run lint
      - name: print success
        run: echo "lint success"
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run test
        run: |
          cd 04_project/04_Practice_Project
          npm install
          npm run test
      - name: print success
        run: echo "test success"
  run-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run build
        run: |
          cd 04_project/04_Practice_Project
          npm install
          npm run build
      - name: print success
        run: echo "build success"
  deploy:
    runs-on: ubuntu-latest
    needs: [run-lint, run-test, run-build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy
        run: |
          cd 04_project/04_Practice_Project
          npm install
          npm run preview
      - name: print success
        run: echo "deploy success"
