# This is a basic workflow to help you get started with Actions

name: code-deployment
on: push
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install node js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: run lint
        run: npm run lint
      - name: print success
        run: echo "lint success"
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install node js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: run test
        run: npm run test
      - name: print success
        run: echo "test success"
  run-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install node js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: run build
        run: npm run build
      - name: print success
        run: echo "build success"
  deploy:
    runs-on: ubuntu-latest
    needs: [run-lint, run-test, run-build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install node js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: deploy
        run: npm run deploy
      - name: print success
        run: echo "deploy success"
