name: Java CI with Maven 
env:
  NAME: 'My Action' 
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    env:
        NAME: 'My Action 2'
    runs-on: ubuntu-latest

    - name: Print name
      run: echo "$NAME"
      env:
        NAME: 'My Action 3'